{'name': 'PDF & Word Converter Pro | DOCX PDF',
 'version': '19.0.1.0.0',
 'category': 'Productivity/Documents',
 'summary': 'Convert PDF to editable DOCX and DOC/DOCX to PDF securely inside Odoo',
 'description': 'Offline two-way PDF and Word conversion with history, diagnostics, privacy '
                'controls, automatic cleanup and premium UI.',
 'author': 'Odoo Wings',
 'website': 'https://apps.odoo.com/apps/modules/browse?author=Odoo%20Wings',
 'support': 'vsmanoj144@gmail.com',
 'license': 'OPL-1',
 'depends': ['base', 'mail', 'web'],
 'external_dependencies': {'python': ['docx']},
 'data': ['security/converter_security.xml',
          'security/ir.model.access.csv',
          'data/cleanup_cron.xml',
          'views/document_conversion_views.xml',
          'views/converter_menu.xml'],
 'assets': {'web.assets_backend': ['ow_document_converter_pro/static/src/scss/document_converter.scss']},
 'images': ['static/description/banner.png', 'static/description/icon.png'],
 'installable': True,
 'application': True,
 'auto_install': False}
